# Generated by Django 5.1 on 2025-02-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('serum_creatinine', models.FloatField()),
                ('albumin', models.FloatField()),
                ('rbc', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('gfr', models.FloatField()),
                ('ckd_prediction', models.CharField(max_length=10)),
                ('ckd_stage', models.IntegerField(blank=True, null=True)),
                ('treatment_recommendation', models.TextField()),
            ],
        ),
    ]
